apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: my-backendconfig-metric
spec:
  timeoutSec: 7200
  connectionDraining:
    drainingTimeoutSec: 3600

---

apiVersion: v1
kind: Service
metadata:
  name: metric-service-service
  labels:
    app: metric-service
  namespace: default
  annotations:
    cloud.google.com/backend-config: '{"default": "my-backendconfig-metric"}'
spec:
  selector:
    app: metric-service
  ports:
    - protocol: "TCP"
      port: 9194
      targetPort: 9194
      nodePort: 31297
  type: NodePort