apiVersion: v1
kind: Service
metadata:
  name: metric-service-service
  labels:
    app: metric-service
  namespace: default
spec:
  selector:
    app: metric-service
  ports:
    - protocol: "TCP"
      port: 9194
      targetPort: 9194
      nodePort: 31297
  type: NodePort